export const langOptions = [
    {
      id: 1,
      name: "English (US)",
      label: "English (US)",
      value: "en-US",
    },
    {
      id: 2,
      name: "English (UK)",
      label: "English (UK)",
      value: "en-GB",
    },
    {
      id: 3,
      name: "Spanish (Spain)",
      label: "Spanish (Spain)",
      value: "es-ES",
    },
    {
      id: 4,
      name: "Spanish (Mexico)",
      label: "Spanish (Mexico)",
      value: "es-MX",
    },
    {
      id: 5,
      name: "French (France)",
      label: "French (France)",
      value: "fr-FR",
    },
    {
      id: 6,
      name: "German (Germany)",
      label: "German (Germany)",
      value: "de-DE",
    },
    {
      id: 7,
      name: "Italian (Italy)",
      label: "Italian (Italy)",
      value: "it-IT",
    },
    {
      id: 8,
      name: "Portuguese (Portugal)",
      label: "Portuguese (Portugal)",
      value: "pt-PT",
    },
    {
      id: 9,
      name: "Portuguese (Brazil)",
      label: "Portuguese (Brazil)",
      value: "pt-BR",
    },
    {
      id: 10,
      name: "Chinese (Mandarin)",
      label: "Chinese (Mandarin)",
      value: "zh-CN",
    },
    {
      id: 11,
      name: "Japanese",
      label: "Japanese",
      value: "ja-JP",
    },
    {
      id: 12,
      name: "Korean",
      label: "Korean",
      value: "ko-KR",
    },
    {
      id: 13,
      name: "Russian",
      label: "Russian",
      value: "ru-RU",
    },
    {
      id: 14,
      name: "Arabic",
      label: "Arabic",
      value: "ar-SA",
    },
    {
      id: 15,
      name: "Hindi",
      label: "Hindi",
      value: "hi-IN",
    },
    {
      id: 16,
      name: "Bengali",
      label: "Bengali",
      value: "bn-IN",
    },
    {
      id: 17,
      name: "Turkish",
      label: "Turkish",
      value: "tr-TR",
    },
    {
      id: 18,
      name: "Dutch",
      label: "Dutch",
      value: "nl-NL",
    },
    {
      id: 19,
      name: "Swedish",
      label: "Swedish",
      value: "sv-SE",
    },
    {
      id: 20,
      name: "Danish",
      label: "Danish",
      value: "da-DK",
    },
    {
      id: 21,
      name: "Norwegian",
      label: "Norwegian",
      value: "no-NO",
    },
    {
      id: 22,
      name: "Finnish",
      label: "Finnish",
      value: "fi-FI",
    },
    {
      id: 23,
      name: "Polish",
      label: "Polish",
      value: "pl-PL",
    },
    {
      id: 24,
      name: "Czech",
      label: "Czech",
      value: "cs-CZ",
    },
    {
      id: 25,
      name: "Hungarian",
      label: "Hungarian",
      value: "hu-HU",
    },
    {
      id: 26,
      name: "Greek",
      label: "Greek",
      value: "el-GR",
    },
    {
      id: 27,
      name: "Hebrew",
      label: "Hebrew",
      value: "he-IL",
    },
    {
      id: 28,
      name: "Thai",
      label: "Thai",
      value: "th-TH",
    },
    {
      id: 29,
      name: "Vietnamese",
      label: "Vietnamese",
      value: "vi-VN",
    },
    {
      id: 30,
      name: "Malay",
      label: "Malay",
      value: "ms-MY",
    },
];
